title: ccAFv2
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs

url: https://just-the-docs.github.io
aux_links:
  Plaisier Lab: https://github.com/plaisier-lab

just_the_docs:
  custom_css:
    - "docs/custom.css"

